### ISSUE TITLE
Dudas surgidas

### ISSUE THREAD

**Issue by israel-fariza** [israefn/decont#1]
Buenos días Tomás.
Dudas que me han surgido.
Duda 1. En el script download.sh escribes ".....in the first argument ($1),...". ¿No es una pequeña errata que en realidad quiere decir "($url)"?
Duda 2. A la hora de ejecutar el pipeline. ¿Basta con realizar un solo script (el pipeline que nos has dado pero todo completo) y ejecutarlo con un bash desde la terminal? O por el contrario ¿quieres que hagamos 4 scripts (download, index, merge and pipeline) en el que uno va llamando a otro sucesivamente?
Duda 3. Para el cutadapt. Hasta ahora he construido lo que te pongo abajo. Pero tengo muchas dudas sobre si es correcta la definición de sid (sid=$(............)) y la propia estructura de todo el script. Únicamente para que me digas si voy muy mal o alguna pista.
Muchas gracias por las respuestas y un saludo, Tomás.
Israel

# Run cutadapt for all merged files
for fname in out/merged/*.fastq.gz
do
    sid=$(ls out/merged/*.fastq.gz | cut -d "_" -f1 | sed 's:data/::' | sort | uniq)
    mkdir -p log/cutadapt
    mkdir -p out/cutadapt
    cutadapt -m 18 -a TGGAATTCTCGGGTGCCAAGG --discard-untrimmed -o out/cutadapt/${sid}.trimmed.fastq.gz data/${sid}.fastq.gz > log/cutadapt/${sid}.log
done

**Comment by tdido** [comment]
Hola Isra.

1) No, en los scripts bash los argumentos llegan *siempre* como variables con nombres $1, $2, $3, etc, independientemente del nombre que tengan afuera, cuando llamás al script.

2) La estructura del script no debería cambiar: pipelines.sh debe llamar a download.sh, index.sh, y merge.sh. También tiene código que no está en scripts externos, como los loops de cutadapt y STAR.

3) La estructura del `for` está bien. Fijate que `out/merged/.fastq.gz` no te está devolviendo todos los archivos .fastq.gz dentro de `out/merged`: te falta un "*" en alguna parte.
Para probar si funciona, podés escribir desde dentro del workspace el comando `ls out/merged/.fastq.gz` (o con la modificación que le hagas) y ver si te devuelve el listado de archivos que necesitás. Una vez que lo lográs, el argumento (o sea, todo menos el `ls`) es lo que tenés que usar para el `for`.
Una vez que eso está bien, entonces vas a tener los nombres de los archivos dentro de `$fname`, uno por vez en cada vuelta del loop, y esa variable es la que tenés que usar para generar $sid. En lugar de `ls out/merged/.fastq.gz`, usarías la variable `$fname` con algún comando que escriba su contenido y se lo pase por pipe a `cut`, etc.

**Comment by israel-fariza** [comment]
Hola Tomás.
Muchas gracias por las prontas respuestas.
Sí, me dí cuenta de la falta del * en cuanto leí el issue que ya te había enviado. Curiosamente ya lo tenía corregido en el script pero no en el issue que te estaba escribiendo.
Si no he entendido mal, el for quedaría como el escrito abajo.
Muchas gracias y un saludo,
Israel

for fname in out/merged/*.fastq.gz
do
    sid=$(cat fname | cut -d "_" -f1 | sed 's:data/::' | sort | uniq)
    mkdir -p log/cutadapt
    mkdir -p out/cutadapt
    cutadapt -m 18 -a TGGAATTCTCGGGTGCCAAGG --discard-untrimmed -o out/cutadapt/${sid}.trimmed.fastq.gz data/${sid}.fastq.gz > log/cutadapt/${sid}.log
done

**Comment by tdido** [comment]
Hola Isra.

Está muy cerca. Tenés un par de problemas en la extracción del sample id:

1) Te falta un "$" en alguna parte para llamar a una variable.
2) El comando que estás usando (`cat`) extrae el contenido del archivo, cuando lo que vos querés es un comando que simplemente te muestre el nombre del archivo, que es lo que vas a procesar.

**Comment by tdido** [comment]
Ah, un detalle menor: la creación de directorios debería estar fuera del loop, ya que son siempre los mismos.
