### ISSUE TITLE
Examen finalizado

### ISSUE THREAD

**Issue by israel-fariza** [israefn/decont#4]
Hola Tomás.
He finalizado el ejercicio.
Todo parece que se ha ejecutado correctamente salvo la última parte que, como ya te he indicado en el issue anterior, no me reconoce los out/star/... como files or directories. No he logrado encontrar el error aunque he ensayado con varias opciones.
Todo ha sido exportado con conda y se ha realizado un último commit final.
Gracias y un saludo,
Israel

**Comment by tdido** [comment]
Hola Isra. Lamento no contestar antes a las issues, pero como no me las habías asignado no me llegaron notificaciones.

No veo tu código en el repo. ¿Hiciste `git push`?

**Comment by israel-fariza** [comment]
Hola tomás.
Sí no te preocupes. Fue un fallo mío.
Pues sí hice git push . En mi git log ya aparecía el commit como "Exam finished".
¿Quieres que lo vuelva a hacer?

**Comment by tdido** [comment]
`git log` te muestra los commits locales, pero no quiere decir que estén en el repo remoto. Probá hacer `git push`.

**Comment by israel-fariza** [comment]
Lo acabo de hacer ¿Ha llegado ahora?

**Comment by tdido** [comment]
Muy bien, Isra, está casi perfecto.

El problema de que no encuentre los logs de STAR es por algo bien pequeño: te falta una "/" al final de esta línea:

https://github.com/israefn/decont/blob/f9bf8ea3617dd621c10b27c1839f8faf6928a03a/scripts/pipeline.sh#L40

La versión correcta del último argumento sería `--outFileNamePrefix out/star/${sid}/`. De otra manera, sin esa barra entiende que no es un directorio sino un prefijo de archivo, y los archivos se llamarían `out/star/C57BL_6NJLog.final.out` en lugar de `out/star/C57BL_6NJ/Log.final.out` (sutil diferencia de la barra entre el sample id y el nombre de archivo).

Una vez corregido eso, lo que te está fallando es el grep de los logs de STAR, simplemente porque el texto que está buscando no existe en los archivos (vos pedís `% of uniquely mapped reads` y en realidad el que existe es `Uniquely mapped reads %`.

Hacé esas correcciones tranquilo, y cuando las tengas debería funcionar todo.

**Comment by israel-fariza** [comment]
Muchas gracias por la explicación, Tomás.
Lo importante para mí es ir comprendiendo los procesos que se van realizando y por qué suceden los mismos, más allá de la nota o de la ejecución de los comandos (que también son importantes, claro).
Me ha resultado un ejercicio difícil. Pero poco a poco vamos aprendiendo a pesar de las lagunas que aún quedan en el proceso del aprendizaje.
Corregiré los errores y ejecutaremos el pipeline.
Saludos cordiales,
Israel

**Comment by tdido** [comment]
Esa es la idea, Isra, y creo que comparando con la posición en la que estabas hace dos semanas, creo que es una gran diferencia. Como te decía, era probable que tuvieras que ponerle buen empeño, pero creo que el resultado es finalmente el esperado :)
